Default: &defaults
  database: tut.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: tut_test.sqlite3
  <<: *defaults

Staging:
  database: tut_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: tut_production.sqlite3
  poolsize: 100
  <<: *defaults